#%RAML 1.0 NamedExample
[{
  movieID: 1,
  movieTitle: "Titanic",
  cinimaCode: "cin-01",
  startingTime: "10AM",
  endingTime: "12AM",
  movieType: "Drama"
},
{
  movieID: 2,
  movieTitle: "Avangers",
  cinimaCode: "cin-02",
  startingTime: "9AM",
  endingTime: "10AM",
  movieType: "Advenchure"
},
{
  movieID: 3,
  movieTitle: "Avater",
  cinimaCode: "cin-01",
  startingTime: "10AM",
  endingTime: "12AM",
  movieType: "Drama"
},
{
  movieID: 4,
  movieTitle: "XYZ",
  cinimaCode: "cin-01",
  startingTime: "10AM",
  endingTime: "12AM",
  movieType: "Drama"
}]